#! /bin/sh

export BSPWM_SCRIPTS_DIR="$HOME/.config/scripts"
export _JAVA_AWT_WM_NONREPARENTING=1

sxhkd &
nitrogen --restore &
numlockx &
picom -b
$HOME/.config/polybar/launch.sh
xrdb -load ~/.Xresources &
clipit &
flameshot &
dunst &
VBoxClient-all &
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width        2
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chrome desktop='^2'
