#! /bin/sh

export BSPWM_SCRIPTS_DIR="$HOME/.config/scripts"
export _JAVA_AWT_WM_NONREPARENTING=1

sxhkd &
nitrogen --restore &
numlockx &
picom -b
$HOME/.config/polybar/launch.sh
devilspie -a &
xrdb -load ~/.Xresources &
clipit &
flameshot &
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

$BSPWM_SCRIPTS_DIR/enforce_monitor_position DP-4 '^1' &
bspc monitor DP-4 -d 1 2 3 4 5 
bspc monitor DP-2 -d 6 7 8 9 10 

bspc config border_width        2
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus true

bspc rule -a Code:code -o desktop='^3'
#code &

bspc rule -a Google-chrome:crx_hjaljckdchhjkhikmngilafdecmnjifi -o desktop='^6'
#google-chrome-stable --profile-directory=Default --app-id=hjaljckdchhjkhikmngilafdecmnjifi &

bspc rule -a Google-chrome:google-chrome -o desktop='^6' split_ratio=0.18
#google-chrome-stable &

$BSPWM_SCRIPTS_DIR/autostart.sh &

